feeds.importer.*:
  type: config_entity
  label: 'Feed importer'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    import_period:
      type: integer
      label: 'The import period'
    fetcher:
      type: string
      label: 'Fetcher id'
    fetcher_configuration:
      type: mapping
      label: 'Fetcher configuration'
    parser:
      type: string
      label: 'Parser id'
    parser_configuration:
      type: mapping
      label: 'Parser configuration'
    processor:
      type: string
      label: 'Processor id'
    processor_configuration:
      type: mapping
      label: 'Processor configuration'

action.configuration.feeds_feed_delete_action:
  type: action_configuration_default
  label: 'Delete feeds configuration'
